AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AwesomeCalculator:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: index.handler
      FunctionName: awesome-calculator
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
        Hooks:
          PreTraffic: !Ref AwesomeCalculatorValidator
      Events:
        Add:
          Type: Api
          Properties:
            Path: /
            Method: GET

  AwesomeCalculatorValidator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: validate.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
          - Effect: "Allow"
            Action:
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
            Resource: 
                !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:awesome-calculator'
      Runtime: nodejs6.10
      FunctionName: 'CodeDeployHook_AwesomeCalculatorValidator'
      DeploymentPreference:
        Enabled: false
      Environment:
        Variables:
          TestVersion: !Sub "${AwesomeCalculator.Version}"          