AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CalculatorAdd:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: calculator
      FunctionName: calculator-add
      AutoPublishAlias: live
      Events:
        Add:
          Type: Api
          Properties:
            Path: /
            Method: GET







#     DeploymentPreference:
#       Type: Canary10Percent5Minutes, Linear10PercentEvery1Minute, etc.
#       Alarms: 
#         !Ref: RollbackAlarm
#       Hooks:       
#         PreTraffic: !Ref ValidatorFunction
#         PostTraffic: !Ref NextStageHook







      DeploymentPreference:
        Type: AllAtOnce
        Hooks:
          PreTraffic: ##VALIDATORARN##

