AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CalculatorAdd:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: calculator
      FunctionName: calculator-add
      Events:
        Add:
          Type: Api
          Properties:
            Path: /
            Method: GET
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
        Hooks:
          PreTraffic: ##VALIDATORARN##

#     DeploymentPreference:
#       Type: Linear10PercentEvery10Minutes
#       Hooks:       
#         PreTraffic: !Ref ValidatorFunction
#         PostTraffic: !Ref NextStageHook
#       Alarms: 
#         !Ref: RollbackAlarm